# Generated by Django 3.2.16 on 2023-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('username', models.CharField(max_length=200, null=True, verbose_name='Kullanıcı Adı')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soyad')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Kullanıcı ID')),
                ('and_date', models.DateTimeField(blank=True, null=True, verbose_name='Gruptan Atılma Zamanı')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bor',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
